apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-with-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-secret
  template:
    metadata:
      labels:
        app: nginx-secret
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: nginx-config
        - secretRef:
            name: app-secret
