apiVersion: v1
kind: Pod
metadata:
 name: pod-with-pvc
spec: 
 containers:
 - name: app
   image: nginx
   volumeMounts:
   - name: persistent-storage
     mountPath: /data
 volumes:
 - name: persistent-storage
   persistentVolumeClaim:
    claimName: my-pvc
