apiVersion: v1
kind: Pod
metadata: 
 name: pod-with-volume
spec:
 containers:
 - name: app
   image: nginx
   volumeMounts:
   - name: my-volume
     mountPath: /data
 volumes:
 - name: my-volume
   emptyDir: {}
